# Generated by Django 6.0 on 2025-12-08 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AQINotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi_value', models.FloatField(help_text='AQI value when notification was sent')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of notification (for daily deduplication)')),
                ('notified_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when notification was sent')),
                ('saved_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='aqi.savedlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aqi_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aqi_notifications',
                'ordering': ['-notified_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='aqi_notific_user_id_c7e8bb_idx'), models.Index(fields=['date'], name='aqi_notific_date_6be718_idx')],
                'unique_together': {('user', 'saved_location', 'date')},
            },
        ),
    ]
