# Generated by Django 5.0.14 on 2025-12-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqi', '0003_citysubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='citysubscription',
            new_name='city_subscr_user_id_57a647_idx',
            old_name='city_subscr_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='citysubscription',
            new_name='city_subscr_is_acti_1ecd03_idx',
            old_name='city_subscr_is_acti_idx',
        ),
        migrations.AlterField(
            model_name='citysubscription',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
