# Generated by Django 5.0.14 on 2025-12-09 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTBrokerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='127.0.0.1', help_text='MQTT broker host/IP address', max_length=255)),
                ('port', models.IntegerField(default=1883, help_text='MQTT broker port')),
                ('topic', models.CharField(default='sensor/data', help_text='MQTT topic to subscribe to', max_length=255)),
                ('username', models.CharField(blank=True, help_text='MQTT username (optional)', max_length=255, null=True)),
                ('password', models.CharField(blank=True, help_text='MQTT password (optional)', max_length=255, null=True)),
                ('client_id', models.CharField(blank=True, help_text='MQTT client ID (optional)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MQTT Broker Configuration',
                'verbose_name_plural': 'MQTT Broker Configurations',
                'db_table': 'mqtt_broker_configs',
                'indexes': [models.Index(fields=['user'], name='mqtt_broker_user_id_9243c4_idx'), models.Index(fields=['is_active'], name='mqtt_broker_is_acti_5929a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', models.JSONField(blank=True, help_text='Raw sensor payload from MQTT', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius (from temp_c)', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity percentage', null=True)),
                ('co_ppm', models.FloatField(blank=True, help_text='Carbon Monoxide in ppm (from mq7_co)', null=True)),
                ('co2_ppm', models.FloatField(blank=True, help_text='Carbon Dioxide in ppm (from mq135_co2)', null=True)),
                ('ch4_ppm', models.FloatField(blank=True, help_text='Methane in ppm (from mq4_ch4)', null=True)),
                ('calculated_aqi', models.IntegerField(blank=True, db_index=True, help_text='Calculated AQI value', null=True)),
                ('aqi_category', models.CharField(blank=True, help_text='AQI category (Good, Moderate, etc.)', max_length=50, null=True)),
                ('aqi_color', models.CharField(blank=True, help_text='AQI color code', max_length=20, null=True)),
                ('dominant_pollutant', models.CharField(blank=True, help_text='Dominant pollutant used for AQI calculation', max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this sensor reading', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'db_table': 'sensor_readings',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['user', 'received_at'], name='sensor_read_user_id_9814fe_idx'), models.Index(fields=['received_at'], name='sensor_read_receive_48d8e1_idx'), models.Index(fields=['calculated_aqi'], name='sensor_read_calcula_0bcef8_idx')],
            },
        ),
    ]
